### ISSUE TITLE
"type" property must be set to "desktop-application"

### ISSUE THREAD

**Issue by bam80** [flathub/com.dosbox.DOSBox#11]
https://github.com/flathub/com.dosbox.DOSBox/blob/7c8fc3e54ff8a26f0247f5e4909ad59c2ccdaeae/com.dosbox.DOSBox.appdata.xml#L3

[File specification](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html#spec-appdata-filespec), see Note:

> The desktop-application component type is the same as the desktop component type - desktop is the older type identifier for desktop-applications and should not be used for new metainfo files, unless compatibility with very old AppStream tools (pre 2016) is still wanted.

**Comment by TingPing** [comment]
Your definition of "must" is wrong. It clearly says `"desktop"` is valid.

**Comment by bam80** [comment]
>Note that the XML root must have the type property set to desktop-application

**Comment by TingPing** [comment]
> The desktop-application component type is the same as the desktop component type
