### ISSUE TITLE
mounting CUE/BIN image is not supported

### ISSUE THREAD

**Issue by bam80** [flathub/com.dosbox.DOSBox#12]
Probably due DOSBox was compiled without SDL_sound library, which is essential for this functionality.

Sample .CUE file:
```
$ cat lba2.dat 
FILE "LBA2.GOG" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
FILE "LBA2.OGG" MP3
  TRACK 02 AUDIO
      INDEX 01 00:00:00

**Comment by AsciiWolf** [comment]
Thanks for reporting this! I will look at it when I have some time. Unfortunately, SDL_sound is not a part of the shared-modules. I have created [an issue](https://github.com/flathub/shared-modules/issues/41) to add it.

**Comment by bam80** [comment]
Maybe add new release with description?
https://github.com/flathub/com.dosbox.DOSBox/blob/7c8fc3e54ff8a26f0247f5e4909ad59c2ccdaeae/com.dosbox.DOSBox.appdata.xml#L62

**Comment by AsciiWolf** [comment]
Why? The DOSBox version is still the same.

**Comment by bam80** [comment]
Yes, but people don't aware what has changed.
We could don't change DOSBox version, just change date and add description (or add new release line with the same DOSBox version)

@TingPing what do you think how we should do better?
