### ISSUE TITLE
Use from others Flatpaks?

### ISSUE THREAD

**Issue by bam80** [flathub/com.dosbox.DOSBox#4]
Hi, I'm newbie in Flatpak.
Can this DOSBox be used from others Flatpaks?
Can they supply .conf files in other than Documents directory?
Sorry if it dumb question not related to this project.

**Comment by AsciiWolf** [comment]
Hi,

I don't think that it is possible to start another Flatpak apps from a Flatpak. But maybe @TingPing will know more about this.

Regarding your second question, unfortunately, no. I don't want to give the DOSBox Flatpak full home directory access.

**Comment by TingPing** [comment]
Not directly, no. They would just bundle what they need.

**Comment by bam80** [comment]
How python apps do this then? Do they need to include python to every app, or it just provided in one of the runtimes?
If latter, can we make something like dosbox runtime?

**Comment by TingPing** [comment]
Python 3 is in the runtime. No you don't need dosbox in a runtime, it would just be built.

**Comment by bam80** [comment]
> Python 3 is in the runtime

@TingPing in which one?
I see here https://www.loganasherjones.com/2018/05/using-flatpak-with-python/ Python is built as a module in script's flatpak.
In the other hand, similar to this project [Winepak](https://github.com/winepak/winepak-sdk-images#structure) uses the runtime to package Wine:

> Winepak is structure in three main parts; the runtime, the wine extensions, and the applications. The core of Winepak is the org.winepak.Platform and org.winepak.Sdk. The Platform & SDK contain the core modules for Winepak and a stable version of Wine, eg. Wine 3.0.

So I'm a little bit confused about in which case we should build a runtime and in which just a module.

**Comment by TingPing** [comment]
> @TingPing in which one?

Every runtime that exists. They just built a newer version.

**Comment by TingPing** [comment]
> So I'm a little bit confused about in which case we should build a runtime and in which just a module.

Are you a platform where you have dozens of applications that are independently maintained (GNOME, KDE)? Then a runtime is cool.

Are you anybody else? Just bundle it probably.

**Comment by bam80** [comment]
> Are you a platform where you have dozens of applications that are independently maintained (GNOME, KDE)? Then a runtime is cool.

Don't you think Wine and DOSBox are those platforms also?

**Comment by TingPing** [comment]
Kinda but I think its a stretch. GNOME contains like 20 libraries, including security sensitive ones, something that would be a pain to bundle and maintain. DOSBox is one module.

**Comment by bam80** [comment]
> DOSBox is one module.

Which used by hundreds of programs.
Well, I starting to think it's the place where Snap wins..

**Comment by TingPing** [comment]
> Well, I starting to think it's the place where Snap wins..

How do you think Snap works? It just bundles the module, it doesn't have a DOSBox runtime...

**Comment by bam80** [comment]
Of course not, but it can connect snaps to each other)

**Comment by TingPing** [comment]
That isn't a commonly used feature and last I used it required manual user connecting thus wasn't very useful.

These are both bundling solutions so you bundle things. That is fine and how its expected to work. You have not mentioned anything about that fact causing an issue.

If enough applications on Flathub want to bundle DOSBox we have a [shared-modules](https://github.com/flathub/shared-modules) repo for shared maintainance. You can also layer applications on each other (referred to as a base) which avoids some build time but at the end of the day is still bundling.

I think the original question has been answered anyway.

**Comment by bam80** [comment]
> These are both bundling solutions so you bundle things.

As I understand, Snaps connection is not bundling. It allows using resources from others snaps, whereas even with the shared-modules repo, the data is copying to each flatpak package independently.

>  You can also layer applications on each other (referred to as a base)

What feature is this? Is it mentioned in documentation, or can you point to the examples maybe?

**Comment by TingPing** [comment]
> As I understand, Snaps connection is not bundling.

But nobody uses that for DOSBox and I can confidently say likely never will.

> What feature is this? Is it mentioned in documentation, or can you point to the examples maybe?

`man flatpak-manifest`, see `base`. It just copies the binaries from another package into itself. Examples:

- https://github.com/flathub/org.electronjs.Electron2.BaseApp
- https://github.com/flathub/io.atom.Atom/blob/master/io.atom.Atom.json#L4-L5

**Comment by bam80** [comment]
> But nobody uses that for DOSBox and I can confidently say likely never will.

Maybe I'm wrong, but I thought DOSBox is a good candidate for this.
Thanks for the examples.

**Comment by TingPing** [comment]
Again last time I used connections they were not automatic which means all users have to run obscure commands to get functioning software. That may be fixed but is not promising.

**Comment by bam80** [comment]
> You can also layer applications on each other (referred to as a base) which avoids some build time but at the end of the day is still bundling.

I don't quite get it if the base app is copied or not. The Doc says about the [Electron base app](http://docs.flatpak.org/en/latest/electron.html?highlight=Base%20apps#the-electron-base-app):

> It also has the advantage of reducing the amount of duplication on users’ machines, since it means that Electron is only saved once on disk.

**Comment by TingPing** [comment]
It is copied but OSTree de-duplciates copies.

**Comment by bam80** [comment]
@TingPing 
Hmm, interesting. I think it should me mentioned in the Documentation somewhere, as it just has no single word about de-duplication right now. How it phrased above is confusing, because what you see at first look on build stage the files are just copied.

**Comment by TingPing** [comment]
@bam80 	This is probably the best information about it: https://blogs.gnome.org/alexl/2017/10/02/on-application-sizes-and-bloat-in-flatpak/

**Comment by bam80** [comment]
@TingPing thanks! I just wanted the official docs would be consistent :)
