### ISSUE TITLE
[RFE] Add MIDI support

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.dosbox.DOSBox#5]
MIDI is currently not supported on this DOSBox Flatpak build. It could be a good idea to add MIDI support using FluidSynth.

**Comment by bam80** [comment]
Do you prefer FluidSynth instead of TiMidity?

**Comment by AsciiWolf** [comment]
FluidSynth would be nice. It is already [used](https://github.com/flathub/org.scummvm.ScummVM/pull/1) in my ScummVM Flatpak.

**Comment by dreamer** [comment]
I am not sure if it was supposed to work or not, but MIDI works without issues on my system (but I tried with both timidity and fluidsynth installed through rpm, not sure about flatpak versions).

Tested with The Ultimate Doom, Steam version, using [steam-dos](https://github.com/dreamer/steam-dos) to turn MIDI on/off automatically in DOSBox.

**Comment by AsciiWolf** [comment]
@dreamer You are right, thanks for pointing this out! The builtin MIDI support is really basic, but seems to be sufficient for most games.
