### ISSUE TITLE
DOSBox Configuration

### ISSUE THREAD

**Issue by mr-falafel** [flathub/com.dosbox.DOSBox#7]
Where do I put a dosbox.conf to configure DOSBox? I have one in ~/documents but it does nothing.

**Comment by mr-falafel** [comment]
Never mind, I didn't think to check the com.dosbox.DOSBox directory for hidden folders. Maybe this can be documented somewhere?

**Comment by AsciiWolf** [comment]
This is a standard Flatpak directory and is [documented](http://docs.flatpak.org/en/latest/conventions.html?highlight=.var%2Fapp) in the Flatpak documentation. Anyway, feel free to make a PR with README.md that documents this.
