### ISSUE TITLE
need help in composing .appdata.xml

### ISSUE THREAD

**Issue by bam80** [flathub/com.dosbox.DOSBox#8]
@TingPing 
Hello, I still new to Flatpak,
but I had success with making my first Flatpak project basing on this one. Thanks @AsciiWolf .
It already works, and now I am planning to publish it.
For that, I need compose .appdata.xml and here is where I need help.
I didn't study closely it yet, but first problem I faced is that I don't have any Flatpak-compatible App Center to test that .appdata.xml.
Is any way I could "debug" my .appdata.xm and see results?
Any advice would be very appreciated, thanks!

**Comment by TingPing** [comment]
> I didn't study closely it yet, but first problem I faced is that I don't have any Flatpak-compatible App Center to test that .appdata.xml.
Is any way I could "debug" my .appdata.xm and see results?

Nope. Either install `gnome-software` or `plasma-discovoer`.

**Comment by bam80** [comment]
Thanks @TingPing for a quick answer.
I see Flathup has Web-rendered data from that .appdata.xml's. Is there any similar Web service I could test my AppData with? Maybe a local service withing container easy to setup?

**Comment by AsciiWolf** [comment]
You can use `appstream-util validate-relax bar.foo.App.appdata.xml` to at least test if the AppData file is valid. ;-)

**Comment by bam80** [comment]
Yes, but I would like to see "rendered" results also..

**Comment by TingPing** [comment]
I mean its all open source but its certainly harder to host a server than install an application.

**Comment by bam80** [comment]
Agree, I just hoped maybe pre-configured Web-server container solution already exists for this..
For application, I need to learn how to build and install it then, because I haven't it in repos for my distro..

**Comment by TingPing** [comment]
It isn't too crazy to build, you should probably make a distro package even if it only handles Flatpaks/GNOME extensions. Kinda a core part of GNOME for like 5 years now..

**Comment by bam80** [comment]
I run Plasma 5. So I need build plasma-discover and somewhat plugin to it for Flatpak support?
I don't know why there is no packages yet. Maybe some distro-specific difficulties?

**Comment by TingPing** [comment]
It comes with a plugin yes: https://github.com/KDE/discover/tree/master/libdiscover/backends/FlatpakBackend

**Comment by bam80** [comment]
Maybe you can tell me what's wrong with this Discover flatpak:
https://github.com/flatpak/flatpak/issues/1207#issuecomment-440502188
I don't know where to ask for help, sorry

**Comment by bam80** [comment]
I have managed to build and run Plasma-Discover from this flatpak(it's broken, had to fix several problems): https://phabricator.kde.org/source/flatpak-kde-applications/browse/master/org.kde.discover.json
Thanks everyone for helping

**Comment by bam80** [comment]
Sorry for offtopic, I can't see AppData of my buit and installed flatpak in  Plasma-Discover.
I see just name, size, etc. - but no description or even icon. For other installed flatpaks I see the data. 
I think I installed AppData xml properly.
What could be the problem, could you help me? Should Plasma-Discover pull local AppData xml from the flatpak itself if no repo data available?
