### ISSUE TITLE
Extra ".desktop" in ID?

### ISSUE THREAD

**Issue by bam80** [flathub/com.dosbox.DOSBox#9]
https://github.com/flathub/com.dosbox.DOSBox/blob/7c8fc3e54ff8a26f0247f5e4909ad59c2ccdaeae/com.dosbox.DOSBox.appdata.xml#L4
According to [Recommended metadata file contents](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-contents), there seem should be no ".desktop" in the ID

**Comment by AsciiWolf** [comment]
The DOSBox Flatpak was made when the old standard was still used. I will fix this in the future update.
